---
abstract: 'Work with Gerrit-specific features in a Git::Repository'
author:
  - 'Nathaniel Nutter <nnutter@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Repository-Plugin-Gerrit
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Git::Repository::Plugin::Gerrit:
    file: lib/Git/Repository/Plugin/Gerrit.pm
    version: 0.04
requires:
  Git::Repository: 1.13
  Git::Repository::Plugin::Log: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/nnutter/Git-Repository-Plugin-Gerrit/issues
  homepage: https://github.com/nnutter/Git-Repository-Plugin-Gerrit
  repository: git://github.com/nnutter/Git-Repository-Plugin-Gerrit.git
version: 0.04
x_contributors:
  - 'Nathaniel Nutter <iam@nnutter.com>'
